---
title: "Log-In Flexdashboard"
author: 
output: 
  flexdashboard::flex_dashboard:
    css: inst/assets/styles-auth.css
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
if(!require(shinymanager)){
  install.packages('shinymanager', dependencies = TRUE, repos = "http://cran.us.r-project.org")
  library(shinymanager)
}
if(!require(shiny)){
  install.packages('shiny', dependencies = TRUE, repos = "http://cran.us.r-project.org")
  library(shiny)
}
if(!require(tidyverse)){
  install.packages('tidyverse', dependencies = TRUE, repos = "http://cran.us.r-project.org")
  library(tidyverse)
}
if(!require(lubridate)){
  install.packages('lubridate', dependencies = TRUE, repos = "http://cran.us.r-project.org")
  library(lubridate)
}
# NEU knitr
if(!require(knitr)){
  install.packages("knitr", dependencies = TRUE, repos = "http://cran.us.r-project.org")
  library(knitr)
}

# define some credentials (you can also use sqlite database)
credentials <- data.frame(
 user = c("shiny", "shinymanager"),
 password = c("vh", "12345"),
 stringsAsFactors = FALSE
)
```

```{r rck1}

auth_ui(id = "auth")

# Q1: How to transform to 'moduleServer'?
auth <- callModule(
   module = auth_server,
   id = "auth" ,
    check_credentials = check_credentials(credentials) # data.frame
   # check_credentials = check_credentials("path/to/credentials.sqlite", passphrase = "supersecret") # sqlite
)


```

```{r rck2}
# Store result of authentification in a reactive variable 
eval_login <- reactive({
     auth$result
     })


```




<!-- does not work: 'isolate(eval_login())' alsway FALSE -->
<!-- ```{r, child="Child_test.Rmd", eval = FALSE} 
``` -->

<!-- does not work: 
Error in : Operation not allowed without an active reactive context.
* You tried to do something that can only be done from inside a reactive consumer. -->
<!-- ```{r, child="Child_test.Rmd", eval = eval_login()}
``` -->

<!-- does not work: 
Error:  ungültiger Argumenttyp -->
<!-- ```{r, child="Child_test.Rmd", eval = reactive(auth$result)}
``` -->

```{r rck3a, echo=FALSE, results='asis', eval = TRUE}
# -------------------------------------------------------------------------
# some tries
# -------------------------------------------------------------------------

# -------------------------------------------------------------------------
# suggestion stackoverflow by ismirsehregal
# https://yihui.org/knitr/options/#chunk-options
# https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html
# https://stackoverflow.com/questions/13327258/is-it-possible-to-share-variables-between-knitr-chunks-using-engine-bash
# https://stackoverflow.com/questions/16827788/knitr-child-throws-error-after-upgrade-to-r-3-0

# Renders as text only
#res <- knitr::knit_child(input= 'Child_test.Rmd', quiet = TRUE)
#reactive({
#  if (auth$result) {
    #cat(res, sep = '\n') # Vorschlag stackoverflow
#  }
#})


# -------------------------------------------------------------------------
# show R Markdown Terminal in Flexdashboard, but do not interpret the Code
#reactive({
#  if (auth$result) {
#    knitr::knit_child(input= 'Child_test.Rmd')#x <- cat(res, sep = '\n')
#  }
#})


# -------------------------------------------------------------------------
# Some further tries
# ... and Error Messages in German :-(

#res <- knitr::knit_child(input= 'Child_test.Rmd', quiet = TRUE)
#reactive({
#  if (auth$result) {
    #cat(eval(parse(cat(res, sep = '\n\n')))) #  'file' muss eine Zeichenkette oder eine Verbindung sein
    #cat(eval(parse(paste(res, sep = '\n')))) #  kann Verbindung nicht öffnen
#  }
#})


# -------------------------------------------------------------------------
# Source RMD-file:
# Idea from:
# https://stackoverflow.com/questions/41962434/source-code-from-rmd-file-within-another-rmd
# runs, but show nothing

#source_rmd <- function(file, local = FALSE, ...){
#  options(knitr.duplicate.label = 'allow')
#
#  tempR <- tempfile(pattern = "file",tmpdir = ".", fileext = ".R")
#  on.exit(unlink(tempR))
#  knitr::purl(file, output=tempR, quiet = TRUE)
#
#  envir <- globalenv()
#  envir <- TRUE
#  source(tempR, local = envir, ...)
#}
#
#reactive({
#  if (auth$result) {
#    source_rmd("Child_test.Rmd")
#  }
#})


```

